# .readthedocs.yml
# Read the Docs configuration file

# Required
version: 2

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python:
      version: 3.12
      install:
        - requirements: requirements.txt  # Ensure dependencies are installed

# Sphinx settings
sphinx:
  configuration: docs/conf.py  # Path to your Sphinx configuration file

# Build formats
formats:
  - pdf
  - epub
