# .readthedocs.yml
# Read the Docs configuration file

# Required
version: 2

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"  # Specify Python version as a string
  install:
    - pip:
        requirements: requirements.txt  # Install dependencies from requirements.txt

# Sphinx settings
sphinx:
  configuration: docs/conf.py  # Path to your Sphinx configuration file

# Build formats
formats:
  - pdf
  - epub
